matrix:
  include:
    - os: linux
      language: c
      script: make
      cache:
        directories:
          - .Makefile.d
          - .reqd
    - os: osx
      language: c
      script: make
      cache:
        directories:
          - .Makefile.d
          - .reqd
    - os: windows
      language: c++
      before_script:
        - export CC=CL.exe
        - export CC_FOR_BUILD="$CC"
        - export CXX=link.exe
        - export CXX_FOR_BUILD="$CXX"
      script:
        - ./bin/build.cmd
      cache:
        directories:
          - deps
notifications:
  email:
    on_success: never
