matrix:
  include:
    - os: linux
      language: c
      script: make
      cache:
        directories:
          - .Makefile.d
          - .reqd
    - os: osx
      language: c
      script: make
      cache:
        directories:
          - .Makefile.d
          - .reqd
    - os: windows
      language: c
      script:
        - ./bin/build.cmd
      cache:
        directories:
          - deps
notifications:
  email:
    on_success: never
